### ISSUE TITLE
d.tube trending tag webpage is empty

### ISSUE THREAD

**Issue by gloschtla** [dtube/dtube#120]
When I click on any of the trending tags, I am forwarded to a page without videos. 

for example this one: https://d.tube/#!/t/blockchain

**Comment by techcoderx** [comment]
Looks like when there is only one video that made the tag trending the search API will not return any result 🤔

**Comment by tibfox** [comment]
somehow it has to do with the ts query parameter. The calculation seams to be correct but even if there is content for the tag after that ts the result set is empty. If I reduce the ts step by step I receive rows. Could it be that the search engine is querying against something else instead of directly against the db? if yes: is there a index job not running? idk

**Comment by skzap** [comment]
fixed for a couple of weeks now
