### ISSUE TITLE
Uploader 1st page: Source selection is black font on dark mode

### ISSUE THREAD

**Issue by tibfox** [dtube/dtube#154]
Dark mode: 
The font color of the 1st page within the uploader is black

![grafik](https://user-images.githubusercontent.com/6019754/80380155-7443cf00-889f-11ea-9a3e-b891e65f1775.png)

**Comment by brishtiteveja** [comment]
This is happening because for some reason ".ui.checkbox + label" is not adding "nightmodetext" as a class when jumping from main page to upload page. However, if you switch to Normal mode and switch back to Night mode again, it works. It's not working only when jumping from the video/front page. It seems like it's a related issue: https://github.com/twbs/bootstrap/issues/26904 I tried adding other css class names to activate, but didn't work.

Rather, I found an easy solution to this by wrapping the labels inside "isInNightMode" or "isInNormalMode". See whether you like this solution when I send the pull request.

**Comment by techcoderx** [comment]
fixed in v1.0 patch
