### ISSUE TITLE
Not able to login on DTube

### ISSUE THREAD

**Issue by aaliadanish0687** [dtube/dtube#156]
Hi, I have created a Dtube account but I am unable to login into my Dtube account. My user name is aaliadanish0687. I have received this message after signup.

Warning: you now own a testnet account. This account will not be ported to the main-net automatically unless you are an airdrop recipient or a token sale investor.

I request you to kindly help me in login my account.

**Comment by tibfox** [comment]
Hello there! Personally I don't know any bug or problem with logging in by using the correct private key. Please make sure you have used it. If yes and you can still not login, please contact me on discord in a direct message - you can find me as tibfox#5331 then we can compare the public key to be sure that you have the correct key pair. Note: I don't wanna know your private key of course. That's just for you but by comparing the pub key we can be sure that you are using the correct private one. I will close the issue here because we will work separately on that via discord
