### ISSUE TITLE
Preadjusted VP percentage changed.

### ISSUE THREAD

**Issue by steeminator3000** [dtube/dtube#169]
Yesterday something strange happened on DTube. I uploaded my podcast and as usual, my self-vote was 5%. About an hour later, I uploaded another video, and unbeknownst to me, the voting % changed to 100%, and all of my VP was consumed. Since we're in testnet, it's not much of a problem, but I did not change the voting %. I reported on this in the past concerning the automatic changing of my voting power to 5% every time I tried to change it, and was told that it was a bug that will be fixed. This time it was different because I have always left it on default at 5%, but this time it changed to 100% and consumed all of my VP. It took me some time to slowly build up 2.5M VP and I can't get that back. It's true that it is my responsibility to check my voting % before I publish, which is what I will do now, but I'm curious to know if this is a bug or is it part of the system?

**Comment by prcolaco** [comment]
Had exactly this problem today. In my case I have the VP configured to 0.1%, because I don't want comments to consume all my VP... but suddenly I commented and it consumed 5% of my VP, without any appeal because comments don't show the VP they will consume... that has happened to me several times already in voting other contents, so I always double-check the slider to see it didn't go to 5% auto-magically, but in a comment it's impossible...
It is even questionable if a comment should auto-vote itself facing this, because one has always the possibility to up-vote it later.
link to comment:
https://d.tube/#!/v/prc/3wp37dvs0hs

**Comment by techcoderx** [comment]
fixed in #249
