### ISSUE TITLE
How to log in a user on localhost?

### ISSUE THREAD

**Issue by vinyll** [dtube/dtube#2]
When running `http://localhost:3000/` and attempting to login with SteemConnect, I am redirected to https://d.tube.

How can I login for testing user account by any mean to localhost?

**Comment by skzap** [comment]
You can either:
* Log in with posting key
* Setup a new app in steemconnect that redirects to your localhost:3000 and make the appropriate changes in the source code

**Comment by AnonymousWebHacker** [comment]
Install my own instance of dtube on a SNET (street network) without internet access. In order to allow the registration of users, do I need an account in smeet?

**Comment by skzap** [comment]
We are not related to steem any longer, we have our own blockchain (see dtube/avalon repo).

But registration system is similar, to create user accounts you need to burn dtube coins, check https://d.tube/newaccount

Otherwise we provide a free 'faucet' signup on https://signup.d.tube, but where the username needs to have 9 characters including 2 digits.

**Comment by AnonymousWebHacker** [comment]
@skzap I formulated my question wrong. I mean that in my SNET, I do not have internet access (such as to register at https://d.tube/newaccount or at https://signup.d.tube). Can I create a registry system that is localhost? I don't have internet access all the time, and neither do my friends
