### ISSUE TITLE
Link tippings to content

### ISSUE THREAD

**Issue by tibfox** [dtube/dtube#209]
It would be an extra motivation to tip more if the total tipping would be visible in the video view. Currently tippings are only transferred to the receiver and have no relation to the content itself. But if a user is tipping inside of the video page we could assume that it is ment to be for the video next to the common rewards.

This suggestion came from discord 0.robinson.1

**Comment by KoalaSlippy** [comment]
i agree because tipping is needed because of upcoming livestream tipping is one of the common thing for streaming to implementing it in the video now will allow users to tip the video which equalize the normal video and also the livestreams equally so that people wont always choose live streams rather then making video so game will run equal

**Comment by techcoderx** [comment]
Closing this as author tip hardfork has been approved
