### ISSUE TITLE
Shorten URL Links

### ISSUE THREAD

**Issue by d00k13dotcom** [dtube/dtube#286]
For sake of easy remembering and sharing having the shortest link possible will be beneficial.

Channel Link Currently:
https://d.tube/#!/c/d00k13

Proposed Channel Link:
https://d.tube/d00k13

Current Video Link:
https://d.tube/#!/v/d00k13/26e4t4m2wd6

Proposed Video Link:
https://d.tube/d00k13/26e4t4m2wd6

It is also aesthetically pleasing￼

**Comment by techcoderx** [comment]
This is technically impossible.

Firstly, the hashbang `/#!` is needed so that the static website can be added to and accessed through IPFS and Skynet without issues with the relative path.

The namespace is already as short as it can get, `/c/` could have been called `/channel/` but it has been shortened to one character. Same goes for `/v/`. What would be the link if the account name is a reserved path such as `trendingvideos`, `hotvideos` or `election`? There are conflicts here as well.
