### ISSUE TITLE
Thumbnail upload

### ISSUE THREAD

**Issue by DevDeckardCain** [dtube/dtube#307]
1. Ability to post IPFS thumbnail instead of generating one in browser
2. Javascript validation of the provided thumbnail CID to ensure sizings

I get that there is a need for a layer between the user and the upload form specifically so that the thumbnails look nice on the page, but the thing is HELLA slow.

It would be much nicer to have some sort of Javascript validation of sizing on IPFS content. That way I can tell the upload page "Here's my CID for the thumbnail", it will go to the gateway, check the sizing, verify that its correct and away we go.

And on a side note, the thumbnail for the video doesn't exist in my archive because it's been altered and assigned a different CID than what I already had :(

**Comment by DaniellMesquita** [comment]
I think that for now, only enable to use a custom thumbnail (its optional, user can leave blank and an thumbnail will be generated on browser).

For then later a feature to ensure sizing of the thumbnail.

> And on a side note, the thumbnail for the video doesn't exist in my archive because it's been altered and assigned a different CID than what I already had :(

Yes, if its happening it should be fixed.

**Comment by ec1oud** [comment]
I've been generating thumbnails locally by capturing a frame from vlc, rescaling/cropping with gimp, and attempting to upload the jpg when I submit a new video.  That's a (minor) PITA, but now thumbnail uploading is broken, so I can't post any more videos until that's fixed at least.

I'd have expected to be able to save the thumbnail to ipfs locally and then use the hash, just as with the video itself; that's not so simple, but at least it's scriptable I suppose.  Except maybe I want to interactively choose a representative frame from the video rather than just choosing the first frame or something, which brings up the need for a graphical UI.  If I wrote a graphical client for doing this, I'd probably try to do it with Qt.  Not sure it's worth the trouble until it's clear that d.tube is here to stay, is a stable platform, that things like this don't just break, like what's happening now; and that the API isn't too much trouble to use from non-web-based clients (i.e. don't make me bundle a bunch of JS code just to log in).

It has been said that there's uploader.oneloved.tube so maybe the expectation is that almost everyone uses it.  I don't have it because 1) it appears that it prioritizes payment for hosting of videos on "their" storage, which is against the spirit of what d.tube is supposed to be enabling (else, why is the page highlighting a storage price and a "sign up" button?) 2) there's no Arch Linux package for this client, AFAICT (not even AUR) 3) I'm not fond of electron apps.  If you think you need a browser UI, then why package an app?  Just make a functional web site in the first place, so that I can use my browser of choice.  There are still plenty of people who will refuse to run ipfs locally, and therefore there's still a big market for the storage hosting service.

A functional web site should indeed choose a thumbnail and rescale it by default when I give the IPFS hash to my video.  And it should also allow choosing a different frame from the video.  Then there's no need to install anything or script anything: just ipfs add my-video.mp4, paste the hash into the web page and do the rest of the interaction from there.

**Comment by DevDeckardCain** [comment]
> I've been generating thumbnails locally by capturing a frame from vlc, rescaling/cropping with gimp, and attempting to upload the jpg when I submit a new video. That's a (minor) PITA, but now thumbnail uploading is broken, so I can't post any more videos until that's fixed at least.
> 
> I'd have expected to be able to save the thumbnail to ipfs locally and then use the hash, just as with the video itself; that's not so simple, but at least it's scriptable I suppose. Except maybe I want to interactively choose a representative frame from the video rather than just choosing the first frame or something, which brings up the need for a graphical UI. If I wrote a graphical client for doing this, I'd probably try to do it with Qt. Not sure it's worth the trouble until it's clear that d.tube is here to stay, is a stable platform, that things like this don't just break, like what's happening now; and that the API isn't too much trouble to use from non-web-based clients (i.e. don't make me bundle a bunch of JS code just to log in).
> 
> It has been said that there's uploader.oneloved.tube so maybe the expectation is that almost everyone uses it. I don't have it because 1) it appears that it prioritizes payment for hosting of videos on "their" storage, which is against the spirit of what d.tube is supposed to be enabling (else, why is the page highlighting a storage price and a "sign up" button?) 2) there's no Arch Linux package for this client, AFAICT (not even AUR) 3) I'm not fond of electron apps. If you think you need a browser UI, then why package an app? Just make a functional web site in the first place, so that I can use my browser of choice. There are still plenty of people who will refuse to run ipfs locally, and therefore there's still a big market for the storage hosting service.
> 
> A functional web site should indeed choose a thumbnail and rescale it by default when I give the IPFS hash to my video. And it should also allow choosing a different frame from the video. Then there's no need to install anything or script anything: just ipfs add my-video.mp4, paste the hash into the web page and do the rest of the interaction from there.

What I'm working on now is a system where it will automatically post it to your IPFS node through JS, this way it looks like a traditional file upload, but its not :P Code to come in the coming weeks, until then the thumbnail uploader is reportedly working again
