### ISSUE TITLE
Username login page says it requires 2 numbers, but it requires 3 to continue.

### ISSUE THREAD

**Issue by QazCetelic** [dtube/dtube#363]
And why does a username require numbers in the first place?

**Comment by MrFasolo97** [comment]
Are you sure it requires 3 numbers and not just another character? For example my usual username "fasolo97" isn't made with enough characters, I could go with "fasolo971" or "fasolob97" for example.
It is required because of username value, once claimed it's yours forever, or untill you choose to sell it.
Also making a new username without official account permissions has a cost, see here: [](https://avalonblocks.com/#/accountprice)
Think about it as an anti-spam mechanism, needed because nobody could take away your username from you.
There are multiple examples of users that signed-up for free, funded their account and then made another account with their desired username.
Anyway, could you confirm that it is requiring 3 digits and not 2 with more letters?

**Comment by QazCetelic** [comment]
It indeed wasn't caused by the amount of numbers, it worked after retrying again with the same username. It might have been due to connection issues?
